help_txt = '''

texmatch.py - tex brace checker

Generated by ChatGPT on 2025/03/12

This script checks a .tex file for unmatched pairs of {}, [], (), and ''.
It prints out a message like
    Unmatched opening '{' at line 38, column 11:
followed by the fragments of text with unmatched pair.

Usage: python texmatch.py file.tex
'''

import sys

def check_tex_file(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    stack = []
    openers = {'{': '}', '[': ']', '(': ')', "'": "'"}
    closers = {v: k for k, v in openers.items()}
    
    for line_no, line in enumerate(lines, start=1):
        for col_no, char in enumerate(line, start=1):
            if char in openers:
                stack.append((char, line_no, col_no))
            elif char in closers:
                if stack and stack[-1][0] == closers[char]:
                    stack.pop()
                else:
                    print(f"Unmatched closing '{char}' at line {line_no}, " \
                          "column {col_no}:\n  {line.strip()}")
    
    for char, line_no, col_no in stack:
        print(f"Unmatched opening '{char}' at line {line_no}, " \
        "column {col_no}:\n  {lines[line_no - 1].strip()}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(help_txt)
    else:
        check_tex_file(sys.argv[1])
